### ISSUE TITLE
Indexer address not converted to lowercase when using env vars in a selfhosted deployment

### ISSUE THREAD

**Issue by jimwavefive** [vincenttaglia/indexer-tools-v3#3]
If a user is deploying tools locally, their Indexer address is not being checked for formatting and modified to all lowercase if required. This causes the tools interface to malfunction e.g. cannot switch between mutliple indexers.

This malfunctions (cannot switch to the second Indexer as it has capital letters in the Indexer address field)
```
NO_ENV_ACCOUNTS='[ { "address": "0x7bb834017672b1135466661d8dd69c5dd0b3bf51", "name": "W5 PROD", "active": true, "chain": "arbitrum-one", "agentConnect": false, "agentEndpoint": "", "poiQuery": false, "poiQueryEndpoint": "" }, { "address": "0x70E77e6b48D8241fAc901Fbd60F43612f77D8088", "name": "W5 TEST>
```

This works (second Indexer address all in lowercase):
```
NO_ENV_ACCOUNTS='[ { "address": "0x7bb834017672b1135466661d8dd69c5dd0b3bf51", "name": "W5 PROD", "active": true, "chain": "arbitrum-one", "agentConnect": false, "agentEndpoint": "", "poiQuery": false, "poiQueryEndpoint": "" }, { "address": "0x70e77e6b48d8241fac901fbd60f43612f77d8088", "name": "W5 TESTNET", "active": true, "chain": "arbitrum-sepolia", "agentConnect": false, "agentEndpoint": "", "poiQuery": false, "poiQueryEndpoint": "" } ]'
```

**Comment by vincenttaglia** [comment]
Solved with commit 3aabb7f and will be included in the next release. Had to have one more person run into this issue before I got to solving it 😅
